#!/usr/bin/env bash
export PATH="/root/miniforge3/bin:$PATH"
source /root/miniforge3/etc/profile.d/conda.sh
source /root/miniforge3/etc/profile.d/mamba.sh
mamba activate {{ otter_env_name }}
python {{ autograder_dir }}/source/prepare_nbs.py {{ autograder_dir }}/submission/
python {{ autograder_dir }}/source/run_otter.py
